### ISSUE TITLE
注入被测服务，启动服务时，提示nested exception is java.lang.NoClassDefFoundError: io/arex/inst/httpclient/common/HttpClientAdapter

### ISSUE THREAD

**Issue by liaolongfei** [arextest/deployments#10]
![image](https://user-images.githubusercontent.com/6407371/185276535-7f369e6a-dc29-4ffd-8331-353bc71998f3.png)

**Comment by liaolongfei** [comment]
启动命令： java -javaagent:/root/arex-agent-java/arex-agent-jar/arex-agent-0.0.1.jar -Darex.service.name=test  -Darex.storage.service.host=10.2.233.111:8093 -Darex.config.service.host=10.2.233.111:8091  -jar test-service-1.0.0.jar

**Comment by liaolongfei** [comment]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ecwid.consul.v1.ConsulClient]: Factory method 'consulClient' threw exception; nested exception is java.lang.NoClassDefFoundError: io/arex/inst/httpclient/common/HttpClientAdapter
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
        ... 114 common frames omitted
Caused by: java.lang.NoClassDefFoundError: io/arex/inst/httpclient/common/HttpClientAdapter
        at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:1239)
        at com.ecwid.consul.transport.DefaultHttpTransport.<init>(DefaultHttpTransport.java:33)
        at com.ecwid.consul.v1.ConsulRawClient.<clinit>(ConsulRawClient.java:18)
        at com.ecwid.consul.v1.ConsulClient.<init>(ConsulClient.java:140)
        at org.springframework.cloud.consul.ConsulAutoConfiguration.consulClient(ConsulAutoConfiguration.java:68)
        at org.springframework.cloud.consul.ConsulAutoConfiguration$$EnhancerBySpringCGLIB$$a9c2e88d.CGLIB$consulClient$0(<generated>)
        at org.springframework.cloud.consul.ConsulAutoConfiguration$$EnhancerBySpringCGLIB$$a9c2e88d$$FastClassBySpringCGLIB$$c9b527a6.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
        at org.springframework.cloud.consul.ConsulAutoConfiguration$$EnhancerBySpringCGLIB$$a9c2e88d.consulClient(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 115 common frames omitted

**Comment by mr3** [comment]
We are working on a fix this problem.
